#!/bin/sh
# Render the release's Homebrew formula and push it to the org tap.
# Requires: HOMEBREW_TAP_GITHUB_TOKEN (short-lived app installation token,
# minted per release run) and dist/checksums.txt from the goreleaser build.
# The token travels only in a git auth header — never in URLs, output, or
# on-disk config beyond the transient clone's local config.
set -u

VER="${1:?usage: publish-formula.sh <version>}"
VER="${VER#v}"
: "${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN is required}"

SUMS="dist/checksums.txt"
[ -f "$SUMS" ] || {
  echo "missing ${SUMS} — run the release build first" >&2
  exit 1
}

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
WORK=$(mktemp -d) || exit 1
trap 'rm -rf "$WORK"' EXIT

sh "${SCRIPT_DIR}/render-formula.sh" "$VER" "$SUMS" > "${WORK}/claude-statusline.rb" || exit 1

AUTH=$(printf 'x-access-token:%s' "$HOMEBREW_TAP_GITHUB_TOKEN" | base64 | tr -d '\n')
git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic ${AUTH}" \
  clone --quiet --depth 1 https://github.com/mitre/homebrew-tap.git "${WORK}/tap" || {
  echo "tap clone failed" >&2
  exit 1
}

mkdir -p "${WORK}/tap/Formula"
cp -f "${WORK}/claude-statusline.rb" "${WORK}/tap/Formula/claude-statusline.rb"

cd "${WORK}/tap"
if git diff --quiet --exit-code; then
  if [ -z "$(git status --porcelain)" ]; then
    echo "formula unchanged for v${VER} — nothing to publish"
    exit 0
  fi
fi
git add Formula/claude-statusline.rb
git -c user.name="mitre-tap-publisher[bot]" \
  -c user.email="4314843+mitre-tap-publisher[bot]@users.noreply.github.com" \
  commit --quiet -m "claude-statusline ${VER}

Generated by mitre/claude-statusline release automation."
git -c "http.https://github.com/.extraheader=AUTHORIZATION: basic ${AUTH}" \
  push --quiet origin HEAD:main
echo "published Formula/claude-statusline.rb (v${VER}) to mitre/homebrew-tap"
