#!/bin/sh
# Render the Homebrew formula for a release: version + checksums.txt in,
# formula on stdout. Refuses if any of the four platform assets is missing
# from the checksums file — a partial formula would break that platform.
# Pure rendering, no network; golden-tested from plugin_scripts_test.go.
set -u

VER="${1:?usage: render-formula.sh <version> <checksums-file>}"
SUMS="${2:?usage: render-formula.sh <version> <checksums-file>}"
VER="${VER#v}"
BASE="https://github.com/mitre/claude-statusline/releases/download/v${VER}"

sum_for() {
  awk -v n="claude-statusline-${VER}-$1.tar.gz" '$2 == n { print $1 }' "$SUMS"
}

DARWIN_ARM=$(sum_for darwin-arm64)
DARWIN_AMD=$(sum_for darwin-amd64)
LINUX_ARM=$(sum_for linux-arm64)
LINUX_AMD=$(sum_for linux-amd64)
for pair in "darwin-arm64:$DARWIN_ARM" "darwin-amd64:$DARWIN_AMD" "linux-arm64:$LINUX_ARM" "linux-amd64:$LINUX_AMD"; do
  [ -n "${pair#*:}" ] || {
    echo "missing checksum for ${pair%%:*} in ${SUMS}" >&2
    exit 1
  }
done

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh — do not edit by hand.
# Changes land via the next release of mitre/claude-statusline.
class ClaudeStatusline < Formula
  desc "Fast, configurable status line for Claude Code"
  homepage "https://github.com/mitre/claude-statusline"
  version "${VER}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE}/claude-statusline-${VER}-darwin-arm64.tar.gz"
      sha256 "${DARWIN_ARM}"
    else
      url "${BASE}/claude-statusline-${VER}-darwin-amd64.tar.gz"
      sha256 "${DARWIN_AMD}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${BASE}/claude-statusline-${VER}-linux-arm64.tar.gz"
      sha256 "${LINUX_ARM}"
    else
      url "${BASE}/claude-statusline-${VER}-linux-amd64.tar.gz"
      sha256 "${LINUX_AMD}"
    end
  end

  def install
    bin.install "claude-statusline"
  end

  def caveats
    <<~EOS
      Point Claude Code at the binary in ~/.claude/settings.json:
        "statusLine": {"type": "command", "command": "#{opt_bin}/claude-statusline", "padding": 0}
      Or install via the Claude Code plugin and run /claude-statusline:setup.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-statusline --version")
  end
end
EOF
