# typed: false
# frozen_string_literal: true

# Generated by scripts/render-formula.sh — do not edit by hand.
# Changes land via the next release of mitre/claude-statusline.
class ClaudeStatusline < Formula
  desc "Fast, configurable status line for Claude Code"
  homepage "https://github.com/mitre/claude-statusline"
  version "9.9.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v9.9.9/claude-statusline-9.9.9-darwin-arm64.tar.gz"
      sha256 "2222222222222222222222222222222222222222222222222222222222222222"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v9.9.9/claude-statusline-9.9.9-darwin-amd64.tar.gz"
      sha256 "1111111111111111111111111111111111111111111111111111111111111111"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/mitre/claude-statusline/releases/download/v9.9.9/claude-statusline-9.9.9-linux-arm64.tar.gz"
      sha256 "4444444444444444444444444444444444444444444444444444444444444444"
    else
      url "https://github.com/mitre/claude-statusline/releases/download/v9.9.9/claude-statusline-9.9.9-linux-amd64.tar.gz"
      sha256 "3333333333333333333333333333333333333333333333333333333333333333"
    end
  end

  def install
    bin.install "claude-statusline"
  end

  def caveats
    <<~EOS
      Point Claude Code at the binary in ~/.claude/settings.json:
        "statusLine": {"type": "command", "command": "#{opt_bin}/claude-statusline", "padding": 0}
      Or install via the Claude Code plugin and run /claude-statusline:setup.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-statusline --version")
  end
end
